name: food_order_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  lottie: ^3.0.0
  curved_navigation_bar: ^1.0.1
  carousel_slider: ^5.1.1
  file_picker_cross: ^4.4.2
  image_picker: ^0.8.7+5
  sqflite: ^2.0.2
  path_provider: ^2.0.3
  intl: ^0.20.2
  share_plus: ^4.5.3
  share_plus_linux: ^3.0.1
  share_plus_macos: ^3.0.1
  share_plus_windows: ^3.0.1
  share_plus_web: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/category/
    - assets/discount/
    - assets/food/
    - assets/main/
    - assets/food/hoodie1.png
    - assets/main/avatar1.png
    - assets/catalog/1.jpg
    - assets/catalog/2.jpg
    - assets/catalog/3.jpg
    - assets/catalog/4.jpg
    - assets/catalog/5.jpg
    - assets/catalog/6.jpg
    - assets/catalog/7.jpg
    - assets/catalog/8.jpg
    - assets/catalog/9.jpg
    - assets/catalog/10.jpg
    - assets/catalog/11.jpg
    - assets/catalog/12.jpg
    - assets/catalog/13.jpg
    - assets/catalog/14.jpg
    - assets/catalog/15.jpg
    - assets/catalog/16.jpg
    - assets/catalog/17.jpg
    - assets/catalog/18.jpg
    - assets/catalog/19.jpg
    - assets/catalog/20.jpg
    - assets/catalog/21.jpg
    - assets/catalog/22.jpg
    - assets/catalog/23.jpg
    - assets/catalog/24.jpg
    - assets/catalog/25.jpg
    - assets/catalog/26.jpg
    - assets/catalog/27.jpg
    - assets/catalog/28.jpg
    - assets/catalog/29.jpg
    - assets/catalog/30.jpg
    - assets/catalog/31.jpg
    - assets/catalog/32.jpg
    - assets/catalog/33.jpg
    - assets/catalog/34.jpg
    - assets/catalog/35.jpg
    - assets/catalog/36.jpg
    - assets/catalog/37.jpg
    - assets/catalog/38.jpg
    - assets/catalog/39.jpg
    - assets/catalog/40.jpg
    - assets/catalog/41.jpg
    - assets/catalog/42.jpg
    - assets/catalog/43.jpg
    - assets/catalog/44.jpg
    - assets/catalog/45.jpg
    - assets/catalog/46.jpg
    - assets/catalog/47.jpg
    - assets/catalog/48.jpg